### ISSUE TITLE
Need an appropriate loader to handle this file type for RNBounceable.js

### ISSUE THREAD

**Issue by grousseva** [WrathChaos/react-native-bounceable#1]
node_modules/@freakycoder/react-native-bounceable/build/dist/RNBounceable.js 30:16
Module parse failed: Unexpected token (30:16)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     render() {
|         const { children, style } = this.props;
>         return (<react_native_1.TouchableWithoutFeedback {...this.props} onPress={this.onPress.bind(this, react_native_1.Easing.bounce)}>
|         <react_native_1.Animated.View style={[{ transform: [{ scale: this.state.springValue }] }, style]}>
|           {children}

Do you know why this happening??

**Comment by kuraydev** [comment]
Hello @grousseva 
I have never seen this error. Can you share a minimal reproducible example with me?

**Comment by xdien** [comment]
I also have the same problem
I use **expo** to create the project.
- **sdk42**
- "@freakycoder/react-native-bounceable": "^0.2.5",
- "@freakycoder/react-native-header-view": "^1.2.0",
-  "@freakycoder/react-native-helpers": "^1.0.2",
-  "@freakycoder/react-native-material-textfield": "^1.0.0"

My code:
```
import {ClassicHeader} from "@freakycoder/react-native-header-view";
import * as React from 'react';
import {Dimensions, ScrollView, StyleSheet, TouchableOpacity, View} from 'react-native';
import {Icon} from 'react-native-elements';
const screenWidth = Dimensions.get("window").width;

export default function TabOneScreen() {

  return (
    <ScrollView>
      {/* <DeviceChartRealtime deviceid='e952fb5e-2966'></DeviceChartRealtime> */}
      <View style={styles.container}>
        <ClassicHeader
          headerTitle="Header"
          leftComponent={
            <TouchableOpacity onPress={() => { }}>
              <Icon name="ios-arrow-back" type="Ionicons" size={30} color="blue" />
            </TouchableOpacity>
          }
          rightComponent={
            <TouchableOpacity onPress={() => { }}>
              <Icon name="github" type="AntDesign" size={30} color="purple" />
            </TouchableOpacity>
          }
        />;
      </View>
    </ScrollView>

  );
}


const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 40,
    backgroundColor: 'white',
  },
  paragraph: {
    margin: 24,
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    color: '#34495e',
  },
});
```

What information do you need? give me that command, i will test it and give it to you. sorry I'm new to react and don't know much about debugging!

**Comment by kuraydev** [comment]
Hello @xdien,
You don't even use `@freakycoder/react-native-bounceable` in this code segment. Can you show me the exact error then I can help you. 

Btw, you can use `react-native-helpers` for the ScreenWidth, Height or much more ready to use feature :)

**Comment by xdien** [comment]
I'm trying to use https://github.com/WrathChaos/react-native-header-view to create cardview.  Looks like it's using this module. I will give you error details tomorrow morning

**Comment by kuraydev** [comment]
Which header view are you using? ClassicHeader? You can use https://github.com/WrathChaos/react-native-classic-header

directly a separated library. You do not need to use whole header-view library

**Comment by xdien** [comment]
My problem has been solved. It's a fundamental error because I used the wrong class. I changed it from **@freakycoder/react-native-header-view** to **react-native-classic-header**. thank you!
