### ISSUE TITLE
How do I disable the bouncy?

### ISSUE THREAD

**Issue by UchennaOkafor** [WrathChaos/react-native-bounceable#2]
I want to disable the bounce in certain conditions, how can I do that?
I have tried setting all these props to 0

```
  bounceEffectIn?: number;
  bounceEffectOut?: number;
  bounceVelocityIn?: number;
  bounceVelocityOut?: number;
  bouncinessIn?: number;
  bouncinessOut?: number;
```

but it didn't work

**Comment by kuraydev** [comment]
Hello @UchennaOkafor 

You can use this configuration for looks like disable the bounce effect:

```
bounceEffectIn={1}
bounceEffectOut={1}
bounceVelocityIn={0}
bounceVelocityOut={0}
 ```

**Comment by UchennaOkafor** [comment]
@WrathChaos 

Thank you that works :D
